// lockdiff verifies that a Bazel-generated `.terraform.lock.hcl` (produced
// by the init aspect) is equivalent to a golden lock file generated by real
// `terraform providers lock` or `tofu providers lock`.
//
// The two must agree on:
//
//   - The set of providers (source + registry host)
//   - Version and constraints for each provider
//   - The `zh:` (archive) hash set — the aspect preserves whatever was in the
//     source lock, and the source lock should be the golden itself
//   - At least one of the aspect's `h1:` (directory-content) hashes must
//     appear in the golden's `h1:` set — the aspect only records the `h1:`
//     for the current build platform, whereas the golden may cover several
//
// Exits 0 on match; non-zero with a structured diff otherwise.
package main

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/bazelbuild/rules_go/go/runfiles"
	"rules_terraform/terraform/private/internal/argsfile"
	"rules_terraform/terraform/private/internal/lockparse"
)

const argsEnvVar = "RULES_TERRAFORM_LOCKDIFF_ARGS_FILE"

func main() {
	tokens, err := argsfile.ReadArgv(argsEnvVar)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(2)
	}
	argsfile.Prepend(tokens)

	aspectPath := flag.String("aspect", "", "Runfiles rlocationpath of the aspect-generated .terraform.lock.hcl")
	goldenPath := flag.String("golden", "", "Runfiles rlocationpath of a golden .terraform.lock.hcl produced by real terraform/tofu init")
	regenerateHint := flag.String("regenerate-hint", "", "Command shown in the failure message telling the user how to refresh the golden")
	flag.Parse()

	if *aspectPath == "" || *goldenPath == "" {
		fmt.Fprintln(os.Stderr, "Error: -aspect and -golden are required")
		os.Exit(2)
	}

	r, err := runfiles.New()
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: init runfiles: %v\n", err)
		os.Exit(2)
	}
	resolvedAspect, err := r.Rlocation(*aspectPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: resolve -aspect %q via runfiles: %v\n", *aspectPath, err)
		os.Exit(2)
	}
	resolvedGolden, err := r.Rlocation(*goldenPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: resolve -golden %q via runfiles: %v\n", *goldenPath, err)
		os.Exit(2)
	}

	aspect, err := lockparse.ReadProviderLock(resolvedAspect)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading aspect lock %s: %v\n", resolvedAspect, err)
		os.Exit(2)
	}
	golden, err := lockparse.ReadProviderLock(resolvedGolden)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error reading golden lock %s: %v\n", resolvedGolden, err)
		os.Exit(2)
	}

	problems := diff(aspect, golden)
	if len(problems) == 0 {
		return
	}

	fmt.Fprintf(os.Stderr, "Aspect-generated lock %s does not match golden %s:\n", resolvedAspect, resolvedGolden)
	for _, p := range problems {
		fmt.Fprintf(os.Stderr, "  %s\n", p)
	}
	if *regenerateHint != "" {
		fmt.Fprintf(os.Stderr, "\nRefresh the golden: %s\n", *regenerateHint)
	}
	os.Exit(1)
}

type provKey struct {
	source string
	host   string
}

func indexByKey(entries []lockparse.ProviderEntry) map[provKey]lockparse.ProviderEntry {
	out := make(map[provKey]lockparse.ProviderEntry, len(entries))
	for _, e := range entries {
		out[provKey{source: e.Source, host: e.RegistryHost}] = e
	}
	return out
}

func diff(aspect, golden []lockparse.ProviderEntry) []string {
	aIdx := indexByKey(aspect)
	gIdx := indexByKey(golden)

	var problems []string

	for _, k := range sortedKeys(aIdx) {
		if _, ok := gIdx[k]; !ok {
			problems = append(problems, fmt.Sprintf("aspect has provider %s/%s but golden does not", k.host, k.source))
		}
	}
	for _, k := range sortedKeys(gIdx) {
		if _, ok := aIdx[k]; !ok {
			problems = append(problems, fmt.Sprintf("golden has provider %s/%s but aspect does not", k.host, k.source))
		}
	}

	for _, k := range sortedKeys(aIdx) {
		a := aIdx[k]
		g, ok := gIdx[k]
		if !ok {
			continue
		}
		id := fmt.Sprintf("%s/%s", k.host, k.source)

		if a.Version != g.Version {
			problems = append(problems, fmt.Sprintf("%s: version aspect=%q golden=%q", id, a.Version, g.Version))
		}
		if a.Constraints != g.Constraints {
			problems = append(problems, fmt.Sprintf("%s: constraints aspect=%q golden=%q", id, a.Constraints, g.Constraints))
		}

		if extra := stringSetDiff(a.ZhHashes, g.ZhHashes); len(extra) > 0 {
			problems = append(problems, fmt.Sprintf("%s: aspect has zh: hashes not in golden: %s", id, strings.Join(extra, ", ")))
		}
		if missing := stringSetDiff(g.ZhHashes, a.ZhHashes); len(missing) > 0 {
			problems = append(problems, fmt.Sprintf("%s: golden has zh: hashes not in aspect: %s", id, strings.Join(missing, ", ")))
		}

		if !anyOverlap(a.H1Hashes, g.H1Hashes) {
			problems = append(problems, fmt.Sprintf(
				"%s: no h1: hash overlap. aspect=[%s] golden=[%s] "+
					"(the aspect records h1: for the build platform; golden should cover it)",
				id, strings.Join(a.H1Hashes, ", "), strings.Join(g.H1Hashes, ", "),
			))
		}
	}

	return problems
}

func sortedKeys(m map[provKey]lockparse.ProviderEntry) []provKey {
	out := make([]provKey, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].host != out[j].host {
			return out[i].host < out[j].host
		}
		return out[i].source < out[j].source
	})
	return out
}

func stringSetDiff(a, b []string) []string {
	bs := make(map[string]bool, len(b))
	for _, x := range b {
		bs[x] = true
	}
	var out []string
	for _, x := range a {
		if !bs[x] {
			out = append(out, x)
		}
	}
	sort.Strings(out)
	return out
}

func anyOverlap(a, b []string) bool {
	bs := make(map[string]bool, len(b))
	for _, x := range b {
		bs[x] = true
	}
	for _, x := range a {
		if bs[x] {
			return true
		}
	}
	return false
}
