load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("//terraform/private:format.bzl", "terraform_formatter")
load("//terraform/private:toolchain.bzl", "current_terraform_binary", "current_terraform_toolchain")

package(default_visibility = ["//visibility:public"])

exports_files([
    "defs.bzl",
    "extensions.bzl",
    "terraform_binary.bzl",
    "terraform_fmt_aspect.bzl",
    "terraform_fmt_test.bzl",
    "terraform_module.bzl",
    "terraform_modules_lock.bzl",
    "terraform_provider.bzl",
    "terraform_provider_group.bzl",
    "terraform_test.bzl",
    "terraform_validate_aspect.bzl",
    "terraform_validate_test.bzl",
])

toolchain_type(
    name = "toolchain_type",
)

current_terraform_toolchain(
    name = "current_terraform_toolchain",
)

current_terraform_binary(
    name = "terraform",
)

terraform_formatter(
    name = "format",
)

bzl_library(
    name = "defs_bzl",
    srcs = ["defs.bzl"],
    deps = [
        ":extensions_bzl",
        ":terraform_binary_bzl",
        ":terraform_fmt_aspect_bzl",
        ":terraform_fmt_test_bzl",
        ":terraform_module_bzl",
        ":terraform_modules_lock_bzl",
        ":terraform_provider_bzl",
        ":terraform_provider_group_bzl",
        ":terraform_test_bzl",
        ":terraform_validate_aspect_bzl",
        ":terraform_validate_test_bzl",
    ],
)

bzl_library(
    name = "extensions_bzl",
    srcs = ["extensions.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_binary_bzl",
    srcs = ["terraform_binary.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_fmt_aspect_bzl",
    srcs = ["terraform_fmt_aspect.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_fmt_test_bzl",
    srcs = ["terraform_fmt_test.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_module_bzl",
    srcs = ["terraform_module.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_modules_lock_bzl",
    srcs = ["terraform_modules_lock.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_provider_bzl",
    srcs = ["terraform_provider.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_provider_group_bzl",
    srcs = ["terraform_provider_group.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_test_bzl",
    srcs = ["terraform_test.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_validate_aspect_bzl",
    srcs = ["terraform_validate_aspect.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)

bzl_library(
    name = "terraform_validate_test_bzl",
    srcs = ["terraform_validate_test.bzl"],
    deps = ["//terraform/private:bzl_lib"],
)
