load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "argsfile",
    srcs = ["argsfile.go"],
    importpath = "rules_terraform/terraform/private/internal/argsfile",
    visibility = [
        "//terraform/private:__subpackages__",
        "//tests/private:__subpackages__",
    ],
    deps = ["@rules_go//go/runfiles"],
)
