load("//opentofu:opentofu_binary.bzl", "opentofu_binary")
load("//opentofu:opentofu_fmt_test.bzl", "opentofu_fmt_test")
load("//opentofu:opentofu_validate_test.bzl", "opentofu_validate_test")
load("//terraform:terraform_binary.bzl", "terraform_binary")
load("//terraform:terraform_fmt_test.bzl", "terraform_fmt_test")
load("//terraform:terraform_module.bzl", "terraform_module")
load("//terraform:terraform_validate_test.bzl", "terraform_validate_test")

terraform_module(
    name = "with_modules",
    srcs = glob(["*.tf"]),
    deps = [
        "//tests/with_modules/modules/network",
        "//tests/with_modules/modules/storage",
    ],
)

terraform_binary(
    name = "terraform",
    root = ":with_modules",
)

terraform_validate_test(
    name = "with_modules_test",
    target = ":with_modules",
)

terraform_fmt_test(
    name = "with_modules_fmt_test",
    target = ":with_modules",
)

opentofu_binary(
    name = "tofu",
    root = ":with_modules",
)

opentofu_validate_test(
    name = "with_modules_tofu_test",
    target = ":with_modules",
)

opentofu_fmt_test(
    name = "with_modules_tofu_fmt_test",
    target = ":with_modules",
)
